name: new_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  google_sign_in: ^6.3.0
  local_auth: ^2.3.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  toastification: ^3.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  animated_notch_bottom_bar: ^1.0.3
  flutter_blue_plus: ^1.35.3
  lottie: ^3.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint:
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2

flutter_native_splash:
  color: "#FFCC00"
  image: assets/images/pokemon-png.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pokeball.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokeball.png
    - assets/images/pokemon-png.png
    - assets/images/pokeballz.svg
    - assets/images/poke-types/
    - .env
